CREATE TABLE IF NOT EXISTS developers (
    id SERIAL PRIMARY KEY,
    display_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    github VARCHAR(100) NOT NULL
)

CREATE TABLE IF NOT EXISTS 